{% set name = "ipyflow-core" %}
{% set version = "0.0.178" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ipyflow-core-{{ version }}.tar.gz
  sha256: 4ae1707bce4b768c98e575a46b5a01216b19639bfca885c5fc8e3d5ae0323b92

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - setuptools >=48
    - wheel >=0.30.0
    - setuptools-git-versioning
    - pip
  run:
    - python >=3.6
    - astunparse
    - black
    - ipykernel
    - ipython
    - ipywidgets
    - jupyter_client
    - nest-asyncio
    - pyccolo ==0.0.48
    - traitlets

test:
  # Disable test suite for now SDIST missing utils.py
  # source_files:
  #   - test
  imports:
    - ipyflow
  commands:
    - pip check
    # - pytest -vvv --capture=tee-sys test
  requires:
    - pip
    # - pytest

about:
  home: https://github.com/ipyflow/ipyflow
  dev_url: https://github.com/ipyflow/ipyflow/tree/master/core
  summary: Backend package for ipyflow's dataflow functionality
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
