{% set name = "ipyflow-core" %}
{% set version = "0.0.202" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 461ce836f5c6edad7019708832d5948f465bdcaeb1314e4b1e7921f217d56c5a


build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - setuptools >=48
    - wheel >=0.30.0
    - setuptools-git-versioning
    - pip
  run:
    - python >=3.6
    - astunparse
    - black
    - ipykernel
    - ipython
    - ipywidgets
    - jupyter_client
    - nest-asyncio
    - pyccolo ==0.0.66
    - traitlets

test:
  imports:
    - ipyflow
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ipyflow/ipyflow
  dev_url: https://github.com/ipyflow/ipyflow/tree/master/core
  summary: Backend package for ipyflow's dataflow functionality
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
